force-app/main/default/objects/clofor_com_cfs__Container_Info__c/clofor_com_cfs__Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__Container_NO__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HBL_SHIPMENT__c</fullName>
    <label>H B/L SHIPMENT</label>
    <referenceTo>clofor_com_cfs__CustomObject1__c</referenceTo>
    <relationshipName>Container_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/clofor_com_cfs__CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__HAWB__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HAWB__c</fullName>
    <label>HAWB No.</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__HBL__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HBL__c</fullName>
    <inlineHelpText>Import: Refer to th HB/L and input. Export: When ETD is set, automatically generates H B/L Number with the prefix in initial setting. HB/L Number can be modified after insertion.</inlineHelpText>
    <label>H B/L NUMBER</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__HouseBookingNo__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HouseBookingNo__c</fullName>
    <label>HOUSE BOOKING NO</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Master_B_L__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Master_B_L__c</fullName>
    <label>M B/L NUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__MASTER_BOOKINGNO__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__MASTER_BOOKINGNO__c</fullName>
    <inlineHelpText>Input Booking Number from Carrier for FCL and Consolidator for LCL.</inlineHelpText>
    <label>MASTER BOOKING NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__MAWB__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__MAWB__c</fullName>
    <label>MAWB No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebTrackingFormController.cls
public without sharing class WebTrackingFormController {
    @AuraEnabled(cacheable = true)
    public static String getIdShipment(String search, String type){
        if (type == 'boln'){
            System.debug('1234:');
            return [SELECT Id
                FROM clofor_com_cfs__CustomObject1__c
                WHERE clofor_com_cfs__HBL__c = :search OR clofor_com_cfs__HAWB__c = :search
                LIMIT 1].Id;
        }
        if (type == 'bn'){
            return [SELECT Id
                FROM clofor_com_cfs__CustomObject1__c
                WHERE clofor_com_cfs__MASTER_BOOKINGNO__c = :search
                LIMIT 1].Id;
        }
        if (type == 'cn'){
            return [SELECT Id,clofor_com_cfs__HBL_SHIPMENT__c
                FROM clofor_com_cfs__Container_Info__c
                WHERE clofor_com_cfs__Container_NO__c = :search
                LIMIT 1].clofor_com_cfs__HBL_SHIPMENT__c;
        }
        return '';
    }

    @AuraEnabled(cacheable = true)
    public static List<clofor_com_cfs__CustomObject1__c> getListShipment(String search, String type){
        if (type == 'boln'){
            return [SELECT Id, Name, clofor_com_cfs__HBL__c, clofor_com_cfs__HAWB__c, clofor_com_cfs__Master_B_L__c, clofor_com_cfs__MAWB__c, clofor_com_cfs__HouseBookingNo__c, clofor_com_cfs__MASTER_BOOKINGNO__c
                FROM clofor_com_cfs__CustomObject1__c
                WHERE clofor_com_cfs__HBL__c = :search OR clofor_com_cfs__HAWB__c = :search];
        }
        if (type == 'bn'){
            return [SELECT Id, Name, clofor_com_cfs__HBL__c, clofor_com_cfs__HAWB__c, clofor_com_cfs__Master_B_L__c, clofor_com_cfs__MAWB__c, clofor_com_cfs__HouseBookingNo__c, clofor_com_cfs__MASTER_BOOKINGNO__c
                FROM clofor_com_cfs__CustomObject1__c
                WHERE clofor_com_cfs__MASTER_BOOKINGNO__c = :search];
        }
        if (type == 'cn'){
            List<String> lstId = new List<String>(); 
            List<clofor_com_cfs__Container_Info__c> lstCont= [SELECT Id, Name, clofor_com_cfs__HBL_SHIPMENT__c
                FROM clofor_com_cfs__Container_Info__c
                WHERE clofor_com_cfs__Container_NO__c = :search];
            for (clofor_com_cfs__Container_Info__c cont : lstCont){
                lstId.add(cont.clofor_com_cfs__HBL_SHIPMENT__c);
            }
            return [SELECT Id, Name, clofor_com_cfs__HBL__c, clofor_com_cfs__HAWB__c, clofor_com_cfs__Master_B_L__c, clofor_com_cfs__MAWB__c, clofor_com_cfs__HouseBookingNo__c, clofor_com_cfs__MASTER_BOOKINGNO__c
                FROM clofor_com_cfs__CustomObject1__c
                WHERE Id IN :lstId];
        }
        return [SELECT Id, Name, clofor_com_cfs__HBL__c, clofor_com_cfs__HAWB__c, clofor_com_cfs__Master_B_L__c, clofor_com_cfs__MAWB__c, clofor_com_cfs__HouseBookingNo__c, clofor_com_cfs__MASTER_BOOKINGNO__c
        FROM clofor_com_cfs__CustomObject1__c];
    }
}