force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/clofor_com_cfs__AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__SellTankaJPY__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__SellTankaJPY__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input.1. It will refer the amount in Unit Price of Selling(Local) in Service Master Object. 2. If not, take the amount =Unit Price of Selling(USD)×Exchange Rate-Selling</inlineHelpText>
    <label>UNIT PRICE OF SELLING(LOCAL)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Custom_Application_Config__c/fields/clofor_com_cfs__Disabled_Trigger__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Disabled_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/clofor_com_cfs__CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ANRemark__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ANRemark__c</fullName>
    <label>A/N Remark</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__BLtype__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__BLtype__c</fullName>
    <label>House B/L Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ORIGINAL</fullName>
            </value>
            <value>
                <fullName>SURRENDERED</fullName>
            </value>
            <value>
                <fullName>SURRENDERED - NOT YET</fullName>
            </value>
            <value>
                <fullName>WAYBILL</fullName>
            </value>
            <value>
                <fullName>DRAFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__carton__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__carton__c</fullName>
    <inlineHelpText>Synchronized with Sum of Cargo Quantity in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are not null, Cargo Quantity in CNTR IN TRANS is not Null.</inlineHelpText>
    <label>QUANTITY(TOTAL PACKAGES)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__CBM__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CBM__c</fullName>
    <inlineHelpText>Synchronized with Sum of Measurement(CBM) in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are is not null, Measurement(CBM) in CNTR IN TRANS is not null.</inlineHelpText>
    <label>MEASUREMENT(TOTAL CBM)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__CONTAINERSEALNO__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CONTAINERSEALNO__c</fullName>
    <inlineHelpText>Please Entry Container Number and Seal Number in Container Detail Section at bottom. 
Also allow for direct input Container Number and Seal Number only when need to be amended manually.</inlineHelpText>
    <label>CONTAINER NO/SEAL NO</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__D_O_type__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__D_O_type__c</fullName>
    <label>D/O Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D/O Less</fullName>
            </value>
            <value>
                <fullName>D/O No.</fullName>
            </value>
            <value>
                <fullName>Attachment (荷渡指示書または専用A/Nあり)</fullName>
            </value>
            <value>
                <fullName>D/O Original</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ExchangeRate__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ExchangeRate__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Selling Ex-rate for customer. If Default Invoice Issued Date(Default ‘Today’) is in the period of active EX-Rate Mgmt record, ex-rate is automatically synchronized. Default Invoice Issued Date can be updated from Fixed Invoice Issue Date(If Fixed).</inlineHelpText>
    <label>EXCHANGE RATE FOR SELLING</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Item__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Item__c</fullName>
    <inlineHelpText>Describe the Goods as need to be written in B/L</inlineHelpText>
    <label>GOODS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__LoadLocation__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__LoadLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Refer to Master A/N to confirm about loading Warehouse</inlineHelpText>
    <label>CARGO LOADING WAREHOUSE(LOCAL)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>clofor_com_cfs__LoadLocation__c.clofor_com_cfs__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>clofor_com_cfs__LoadLocation__c</referenceTo>
    <relationshipLabel>F/TMS S/O</relationshipLabel>
    <relationshipName>LoadLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Marks_and_Numbers__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Marks_and_Numbers__c</fullName>
    <inlineHelpText>Marks Attachment field is available for adding long list or attachment for Goods detail.</inlineHelpText>
    <label>Marks and Numbers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__No_Of_LoadingConfirmation__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__No_Of_LoadingConfirmation__c</fullName>
    <inlineHelpText>Refer to MA/N and confirm the number for the shipment.</inlineHelpText>
    <label>WAREHOUSE CONFIRMATION NO</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__PersonInCharge__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__PersonInCharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>営業担当</description>
    <label>DOC OPERATOR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesMan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__REFNO__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__REFNO__c</fullName>
    <label>REF NO</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__TransitV__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__TransitV__c</fullName>
    <inlineHelpText>Input the Vessel/Flight before transit(in import case) or after transit(in export case). Transit Vessel/Flight can be automatically inserted from Transit Vessel/Flight in final Transit record in Shipment Order.</inlineHelpText>
    <label>1ST VESSEL/FLIGHT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__TS__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__TS__c</fullName>
    <inlineHelpText>Input the transit port of the shipment. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. Transit Port in final Transit record  will be automatically inserted in this field.</inlineHelpText>
    <label>TRANSIT PORT</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__UnitType__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__UnitType__c</fullName>
    <label>CARGO TYPE(UNIT)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bag</fullName>
            </value>
            <value>
                <fullName>Bale,compressed</fullName>
            </value>
            <value>
                <fullName>Bale,non-compressed</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>Barrel</fullName>
            </value>
            <value>
                <fullName>Basket</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Budle</fullName>
            </value>
            <value>
                <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
            </value>
            <value>
                <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
            </value>
            <value>
                <fullName>Bulk, liquid</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, fineparticles(powders）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, granular particles(grains）</fullName>
            </value>
            <value>
                <fullName>Bulk, solid, large particles(nodules）</fullName>
            </value>
            <value>
                <fullName>Cage</fullName>
            </value>
            <value>
                <fullName>Can,cylindrical</fullName>
            </value>
            <value>
                <fullName>Can,rectangular</fullName>
            </value>
            <value>
                <fullName>Carboy,non-protected</fullName>
            </value>
            <value>
                <fullName>Carboy,protected</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
                <default>true</default>
                <label>Carton</label>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Cask</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Coil</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Crate</fullName>
            </value>
            <value>
                <fullName>Cylinder</fullName>
            </value>
            <value>
                <fullName>DemiJohn,non-protected</fullName>
            </value>
            <value>
                <fullName>DemiJohn, protected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Voy_No__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Voy_No__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__weight__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__weight__c</fullName>
    <inlineHelpText>Synchronized with Sum of Gross Weight(Kg) in CNTR IN TRANS When below conditions meet; Container Mode is FCL, Container Type and Container Q&apos;ty are is not null, Gross Weight(Kg) in CNTR IN TRANS is not null.</inlineHelpText>
    <label>GROSS WEIGHT</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/HouseConsignee__c.field-meta.xml
<CustomField>
    <fullName>HouseConsignee__c</fullName>
    <label>House Consignee</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/HouseNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyParty__c</fullName>
    <label>House Notify Party</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/HouseShipper__c.field-meta.xml
<CustomField>
    <fullName>HouseShipper__c</fullName>
    <label>House Shipper</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ShippingInstructionControllerTest.cls
@isTest
public class ShippingInstructionControllerTest {
	private static clofor_com_cfs__CustomObject1__c shipment{get; set;}  
    private static List<clofor_com_cfs__AnkenMeisai__c> ListBill = new List<clofor_com_cfs__AnkenMeisai__c>();
    private static clofor_com_cfs__AnkenMeisai__c bill = new clofor_com_cfs__AnkenMeisai__c();

    static{
        clofor_com_cfs__Custom_Application_Config__c config =  new clofor_com_cfs__Custom_Application_Config__c(clofor_com_cfs__Disabled_Trigger__c = true);
        insert config;
        
        shipment = new clofor_com_cfs__CustomObject1__c();
        shipment.HouseShipper__c = 'TEST';
        shipment.HouseNotifyParty__c = 'TEST';
        shipment.HouseConsignee__c = 'TEST';
        shipment.clofor_com_cfs__Voy_No__c = 'TEST';
        shipment.clofor_com_cfs__ExchangeRate__c = 123;
        shipment.clofor_com_cfs__D_O_type__c = 'TEST';
        shipment.clofor_com_cfs__No_Of_LoadingConfirmation__c = 'TEST';
        //shipment.clofor_com_cfs__LoadLocation__c = 'TEST';
        shipment.clofor_com_cfs__TS__c = 'TEST';
        shipment.clofor_com_cfs__TransitV__c = 'TEST';
        shipment.clofor_com_cfs__TransitVoyage__c = 'TEST';
        shipment.clofor_com_cfs__ANRemark__c = 'TEST';
        shipment.clofor_com_cfs__REFNO__c = 'TEST';
        //shipment.clofor_com_cfs__PersonInCharge__c = 'TEST';
        shipment.clofor_com_cfs__CONTAINERSEALNO__c = 'TEST';
        shipment.clofor_com_cfs__Marks_and_Numbers__c = 'TEST';
        shipment.clofor_com_cfs__carton__c = 123;
        shipment.clofor_com_cfs__UnitType__c = 'TEST';
        shipment.clofor_com_cfs__Item__c = 'TEST';
        shipment.clofor_com_cfs__weight__c = 123;
        shipment.clofor_com_cfs__CBM__c = 123;
        shipment.clofor_com_cfs__BLtype__c = 'TEST';
               
        //insert shipment;
        bill = new clofor_com_cfs__AnkenMeisai__c();
        //bill.name = shipment.Id;
        bill.clofor_com_cfs__SellTankaJPY__c = 123;
        bill.clofor_com_cfs__SellTankaUSD__c = 456;
        bill.clofor_com_cfs__curr__c = 'JPY';
        // bill.clofor_com_cfs__SellInTaxAmountJPY__c = 123;
        bill.clofor_com_cfs__InsatuyouSyohinEng__c = 'TEST';
        bill.clofor_com_cfs__Suryo__c = 2;
        bill.clofor_com_cfs__ChargeUnitInPrint__c = 'TEST';
        // bill.clofor_com_cfs__SellTaxNum__c = 123;
        // bill.clofor_com_cfs__SellAmountJPN__c = 123;

        //insert bill;
        System.assert(true);
    }

    public static testMethod void test_ShippingInstruction(){
        Test.startTest();
        try{
        ShippingInstructionController control = new ShippingInstructionController();
        }catch(Exception ex){
            
        }
            
        Test.stopTest();
        
    }
    
}