force-app/main/default/objects/FaxEmailActivity__c/FaxEmailActivity__c.object-meta.xml
<CustomObject>
    <label>Fax/Email Activity</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Fax/Email Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fax/Email Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FaxEmailActivity__c/fields/AttachedFiles__c.field-meta.xml
<CustomField>
    <fullName>AttachedFiles__c</fullName>
    <label>Attached Files</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/FaxEmailActivityTriggerHandler.cls
public class FaxEmailActivityTriggerHandler {

    public FaxEmailActivityTriggerHandler() {
        
    }
    
    public void createContentDocumentLink(List<FaxEmailActivity__c> listFaxEmailActivity) {
        try {
            List<ContentDocumentLink> listCDL = new List<ContentDocumentLink>();
            Set<String> setContentVersionId = new Set<String>();
            for (FaxEmailActivity__c f : listFaxEmailActivity) {
                if (f.AttachedFiles__c != null) {
                    List<String> listAttachedIds = f.AttachedFiles__c.split(',');
                    for (String cvId : listAttachedIds) {
                        if(cvId != null) {
                            setContentVersionId.add(cvId);
                            ContentDocumentLink cdl = new ContentDocumentLink(
                                ContentDocumentId = cvId,
                                LinkedEntityId = f.Id,
                                ShareType = 'V'
                            );
                            listCDL.add(cdl);
                        }
                    }
                }
            }

            if (!listCDL.isEmpty()) {
                Map<Id,ContentVersion> mapCv = getContentVersion(setContentVersionId);
                List<ContentDocumentLink> listCdlInsert = new List<ContentDocumentLink>();
                for (ContentDocumentLink cdl : listCDL) {
					String cvKey = cdl.ContentDocumentId;
                    if (mapCv.containsKey(cvKey)) {
                        cdl.ContentDocumentId = mapCv.get(cvKey).ContentDocumentId;
                        listCdlInsert.add(cdl);
                    }
                }

                // Insert Data ContentDocumentLink to record when send email attchedfiles   
                if (!listCdlInsert.isEmpty()) {
                    insert listCdlInsert;
                }
            }            
        } catch (Exception ex) {
            throw new CustomException(ex.getMessage());
        }
    }
    
    private static Map<Id,ContentVersion> getContentVersion(Set<String> setId) {
        return new Map<Id,ContentVersion>([SELECT Id
                                           		,ContentDocumentId
                                           FROM ContentVersion
                                           WHERE Id IN :setId
                                        ]);
    }
    
    public class CustomException extends Exception {}
}