force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/clofor_com_cfs__CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETA__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETA__c</fullName>
    <inlineHelpText>If there is no ETA in Document, confirm with Carrier or Co-loader</inlineHelpText>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETAAtTransitPort__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETAAtTransitPort__c</fullName>
    <inlineHelpText>Input the ETA at Transit Port. If there is multiple transit, choose the number in Multi Transit Required and same number of Transit record will be created. ETA at Transit Port in final Transit record will be automatically inserted in this field.</inlineHelpText>
    <label>ETA AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETD__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__POD__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__POD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>clofor_com_cfs__Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__POL__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__POL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>clofor_com_cfs__Port__c</referenceTo>
    <relationshipName>HBL_SHIPMENTS_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__status__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__status__c</fullName>
    <label>CARGO STATUS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1. [Ex] Receive info</fullName>
            </value>
            <value>
                <fullName>2. [Ex] Booking completed</fullName>
            </value>
            <value>
                <fullName>3. [Ex] SI Issued</fullName>
            </value>
            <value>
                <fullName>4. [Ex] Pick-up cargo</fullName>
            </value>
            <value>
                <fullName>5. [Ex] Customs clearance</fullName>
            </value>
            <value>
                <fullName>6. [Ex] Draft HBL Issued</fullName>
            </value>
            <value>
                <fullName>7. [Ex] Send Pre-alerts</fullName>
            </value>
            <value>
                <fullName>8. [Ex] SUR HBL / Original HBL issued</fullName>
            </value>
            <value>
                <fullName>1. [Im] POL side Handling</fullName>
            </value>
            <value>
                <fullName>2. [Im] Receive Info</fullName>
            </value>
            <value>
                <fullName>3. [Im] Sent Arrival Notice</fullName>
            </value>
            <value>
                <fullName>4. [Im] Released cargo</fullName>
            </value>
            <value>
                <fullName>5. [Im] Customs clearance</fullName>
            </value>
            <value>
                <fullName>6. [Im] On Delivery</fullName>
            </value>
            <value>
                <fullName>7. [Im] Delivered</fullName>
            </value>
            <value>
                <fullName>9. [Ex] POD side Handling</fullName>
            </value>
            <value>
                <fullName>見積 見積書作成中(Under Quotation)</fullName>
            </value>
            <value>
                <fullName>10. [Ex] Deliveried to CNEE</fullName>
            </value>
            <value>
                <fullName>8. [Ex] POD side Handling</fullName>
            </value>
            <value>
                <fullName>9. [Ex] Deliveried to CNEE</fullName>
            </value>
            <value>
                <fullName>3. [Im] Released cargo</fullName>
            </value>
            <value>
                <fullName>4. [Im] Customs clearance</fullName>
            </value>
            <value>
                <fullName>5. [Im] On Delivery</fullName>
            </value>
            <value>
                <fullName>6. [Im] Deliveried</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Vessle__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Vessle__c</fullName>
    <inlineHelpText>Final Vessel or Flight arrived to POD</inlineHelpText>
    <label>VESSEL/FLIGHT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Voy_No__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Voy_No__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/Vessel_Status__c.field-meta.xml
<CustomField>
    <fullName>Vessel_Status__c</fullName>
    <label>Vessel Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[Ex] Depart As expectation</fullName>
            </value>
            <value>
                <fullName>[Ex] Delay</fullName>
            </value>
            <value>
                <fullName>[Ex] Departed</fullName>
            </value>
            <value>
                <fullName>[Ex] Arrvied destination</fullName>
            </value>
            <value>
                <fullName>[Im] Arrive As expectation</fullName>
            </value>
            <value>
                <fullName>[Im] Delay</fullName>
            </value>
            <value>
                <fullName>[Im] Arrived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Port__c/clofor_com_cfs__Port__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__OnlineHelpPorts</customHelpPage>
    <description>Port</description>
    <label>ポートコード</label>
    <nameField>
        <label>Port name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__Transit__c/clofor_com_cfs__Transit__c.object-meta.xml
<CustomObject>
    <label>積替</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>TRANSIT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__Transit__c/fields/clofor_com_cfs__ETAAtTransitPort__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETAAtTransitPort__c</fullName>
    <label>ETA AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Transit__c/fields/clofor_com_cfs__ETDAtTransitPort__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETDAtTransitPort__c</fullName>
    <label>ETD AT TRANSIT PORT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Transit__c/fields/clofor_com_cfs__InOrderOfTransit__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__InOrderOfTransit__c</fullName>
    <label>IN ORDER OF TRANSIT</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Transit__c/fields/clofor_com_cfs__ShipmentOrder__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ShipmentOrder__c</fullName>
    <label>SHIPMENT ORDER</label>
    <referenceTo>clofor_com_cfs__CustomObject1__c</referenceTo>
    <relationshipLabel>TRANSIT</relationshipLabel>
    <relationshipName>TRANSIT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Transit__c/fields/clofor_com_cfs__TransitPort__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__TransitPort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TRANSIT PORT</label>
    <referenceTo>clofor_com_cfs__Port__c</referenceTo>
    <relationshipLabel>TRANSIT</relationshipLabel>
    <relationshipName>TRANSIT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WebTrackingController.cls
public without sharing class WebTrackingController {
    
    @AuraEnabled(cacheable = true)
    public static clofor_com_cfs__CustomObject1__c getShipments(String id){
        List<clofor_com_cfs__CustomObject1__c> results = [SELECT Id, 
        clofor_com_cfs__POL__r.Name, clofor_com_cfs__POD__r.Name, 
        clofor_com_cfs__Vessle__c, 
        clofor_com_cfs__Voy_No__c, 
        clofor_com_cfs__ETD__c, 
        clofor_com_cfs__ETA__c,
        Vessel_Status__c, 
        RecordType.Name,
        clofor_com_cfs__status__c 
                FROM clofor_com_cfs__CustomObject1__c
                WHERE Id = :id];
        if(results.size() > 0){
            return results.get(0);
        } else {
            return null;
        }
        
    }
    @AuraEnabled(cacheable = true)
    public static List<clofor_com_cfs__Transit__c> getTransitsByShipment(String shipmentId){
        return [SELECT Id, clofor_com_cfs__TransitPort__r.Name, 
        clofor_com_cfs__ETDAtTransitPort__c,
        clofor_com_cfs__ETAAtTransitPort__c,
        clofor_com_cfs__InOrderOfTransit__c, 
        clofor_com_cfs__ShipmentOrder__r.Id  
                FROM clofor_com_cfs__Transit__c
                WHERE clofor_com_cfs__ShipmentOrder__r.Id = :shipmentId
                ORDER BY clofor_com_cfs__InOrderOfTransit__c ASC];
    }
    @AuraEnabled(cacheable = true)
    public static List<Boolean> getPositions(String shipmentId){
        List<clofor_com_cfs__Transit__c> transit = getTransitsByShipment(shipmentId);
        
        clofor_com_cfs__CustomObject1__c shipment = getShipments(shipmentId);
        List<Boolean> results = new List<Boolean>();

        Date prevTimeLine = Date.valueOf(shipment.clofor_com_cfs__ETD__c);
        Date lastTimeLine = Date.valueOf(shipment.clofor_com_cfs__ETA__c);
        Date today = system.today();

        if(today <= prevTimeLine){
            results.add(true);
        } else {
            results.add(false);
        }
        if(transit.size() > 0){
            for(Integer i = 0; i<transit.size(); i++){
                 if(today >= Date.valueOf(transit.get(i).clofor_com_cfs__ETAAtTransitPort__c) && today <= Date.valueOf(transit.get(i).clofor_com_cfs__ETDAtTransitPort__c) && ((i+1 <= transit.size()-1 && Date.valueOf(transit.get(i).clofor_com_cfs__ETDAtTransitPort__c) < Date.valueOf(transit.get(i+1).clofor_com_cfs__ETAAtTransitPort__c)) || (i+1 > transit.size()-1))){
                    results.add(false);
                    results.add(true);
                } else if((today > prevTimeLine && (transit.get(i).clofor_com_cfs__ETAAtTransitPort__c == null || today < Date.valueOf(transit.get(i).clofor_com_cfs__ETAAtTransitPort__c))) && today < lastTimeLine){
                    results.add(true);
                    results.add(false);
                } else {
                    results.add(false);
                    results.add(false);
                }
                prevTimeLine = Date.valueOf(transit.get(i).clofor_com_cfs__ETDAtTransitPort__c);
            }
            if(today >= lastTimeLine){
                results.add(false);
                results.add(true);
            } else if((today > prevTimeLine && (shipment.clofor_com_cfs__ETA__c == null || today < lastTimeLine)) && today < lastTimeLine){
                results.add(true);
                results.add(false);
            } else {
                results.add(false);
                results.add(false);
            }
        } else {
            if(today >= lastTimeLine){
                results.add(false);
                results.add(true);
            } else if((today > prevTimeLine && (shipment.clofor_com_cfs__ETA__c == null || today < lastTimeLine)) && today < lastTimeLine){
                results.add(true);
                results.add(false);
            } else {
                results.add(false);
                results.add(false);
            }
        }
        return results;
    }
}