force-app/main/default/objects/Account/fields/Account_Name_JP__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_JP__c</fullName>
    <label>Account Name (JP)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__CompanyShortName__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CompanyShortName__c</fullName>
    <label>Account Short Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__CustomerType__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>clofor_com_cfs__CustomerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__Field1__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/clofor_com_cfs__CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETA__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETA__c</fullName>
    <inlineHelpText>If there is no ETA in Document, confirm with Carrier or Co-loader</inlineHelpText>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETD__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Field1__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/clofor_com_cfs__CustomerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Account</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Customer Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HBLControllerTest.cls
@isTest
public with sharing class HBLControllerTest {
    private static clofor_com_cfs__CustomObject1__c shipment{get; set;}
    public static testMethod void CheckHBLControllerTest() {
        Test.startTest();
        Account ac = new Account(
            Name = 'Customer service',                             // Business Relationship
            Account_Name_JP__c = 'Customer service123123',                                                                   // Account Name
                                                     // Tax Code
                                                  // Customer Type
            clofor_com_cfs__CompanyShortName__c = '495 TO HIEN THANH STR, WARD 14, DISTRICT 10,',  // English Address
            clofor_com_cfs__CustomerType__c = 'Others'                               // Mail
        );
        insert ac;
        
        clofor_com_cfs__CustomObject1__c ship = new clofor_com_cfs__CustomObject1__c(clofor_com_cfs__ETD__c =  Date.newInstance(2021, 1, 1),
                                                  clofor_com_cfs__ETA__c =  Date.newInstance(2021, 3, 20),
                                                                                     clofor_com_cfs__Field1__c = ac.Id);
        insert ship;

        PageReference pageRef = Page.page_HBL;
        pageRef.getParameters().put('Id', ship.Id);
        Test.setCurrentPage(pageRef);
        HBLController fe = new HBLController();
        
        ApexPages.currentPage().getParameters().put('shipmentId', ship.Id);

        List<SelectOption> itemOptions = fe.getSortOptions();
        Test.stopTest();
    }
}