force-app/main/default/objects/Account/fields/Account_Name_JP__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_JP__c</fullName>
    <label>Account Name (JP)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__CompanyShortName__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CompanyShortName__c</fullName>
    <label>Account Short Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__CustomerType__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__CustomerType__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>clofor_com_cfs__CustomerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/clofor_com_cfs__Field1__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Field1__c</fullName>
    <label>TAX PAYMENT TYPE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>立替</fullName>
            </value>
            <value>
                <fullName>ダイレクト口座</fullName>
            </value>
            <value>
                <fullName>延納</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/clofor_com_cfs__AnkenMeisai__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLSBOnlineHelp</customHelpPage>
    <description>H B/L - SELLING/BUYNG</description>
    <label>F/TMS-請求・仕入</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>FMS BILL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__Anken__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Anken__c</fullName>
    <label>H B/L SHIPMENT ID</label>
    <referenceTo>clofor_com_cfs__CustomObject1__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Anken</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ChargeUnit__c</fullName>
    <inlineHelpText>Set in case Charge Unit is different from Charge Unit in Service.</inlineHelpText>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>clofor_com_cfs__UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__Description__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Description__c</fullName>
    <inlineHelpText>This will appear in Debit Note to local customer.</inlineHelpText>
    <label>DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__PrintFlag__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__PrintFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, it will show in the Invoice. If not checked, it will not show in the invoices.</inlineHelpText>
    <label>PRINT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__Seikyusaki__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Seikyusaki__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>INVOICE TO</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerB2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS BILL (INVOICE TO)</relationshipLabel>
    <relationshipName>Seikyusakis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__SellTankaUSD__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__SellTankaUSD__c</fullName>
    <inlineHelpText>This field is input automatically if there is no manual input. 1. It will refer the amount in Unit Price of Selling(USD) in Service Master Object. 2. If not, take the amount =Unit Price of Selling(Local)/Exchange Rate-Selling.</inlineHelpText>
    <label>UNIT PRICE OF SELLING(USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__Suryo__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Suryo__c</fullName>
    <inlineHelpText>Multiplied to Unit Price of Selling(Buying) and automatically calculates Total Amount of Selling(Buying).</inlineHelpText>
    <label>CHARGE UNIT (TOTAL)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__AnkenMeisai__c/fields/clofor_com_cfs__Tariff__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Tariff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Optional Filter criteria: 1 and (2 or 3)
-1:Pricing Name in Pricing: Active equal True
-2:Service Provider Vendor in Pricing equal Payment To-Buying in Invoicing
-3:Target Customer in Pricing equal Invoice To in Invoicing</inlineHelpText>
    <label>PRICING NAME</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>clofor_com_cfs__TariffMaster__c.clofor_com_cfs__ProductFlag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Service: Active status equals True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>clofor_com_cfs__TariffMaster__c</referenceTo>
    <relationshipLabel>F/TMS BILL</relationshipLabel>
    <relationshipName>Tariff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/clofor_com_cfs__Container_Info__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_ContainerInfoOnlineHelp</customHelpPage>
    <description>Changed Label name from コンテナ(container) to CONTAINER &amp; SEAL NO, so as client can know that this is the obeject to input container &amp; seal number.

Aoki</description>
    <label>移動中コンテナ</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>CONTAINER ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__Container__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Container__c</fullName>
    <label>CONTAINER TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
                <default>true</default>
                <label>20&apos;DC</label>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexitank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__Container_NO__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Container_NO__c</fullName>
    <inlineHelpText>Please enter 11digits(4digit container ownership code+7digit container code)</inlineHelpText>
    <label>CONTAINER NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HBL_SHIPMENT__c</fullName>
    <label>H B/L SHIPMENT</label>
    <referenceTo>clofor_com_cfs__CustomObject1__c</referenceTo>
    <relationshipName>Container_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Container_Info__c/fields/clofor_com_cfs__Seal_No__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Seal_No__c</fullName>
    <label>SEAL NUMBER</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Custom_Clearance__c/clofor_com_cfs__Custom_Clearance__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_CustomClearanceOnlineHelp</customHelpPage>
    <description>Custom Clearance</description>
    <label>通関</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Custom Clearance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__Custom_Clearance__c/fields/clofor_com_cfs__HBL_SHIPMENT__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__HBL_SHIPMENT__c</fullName>
    <label>H B/L-SHIPMENT</label>
    <referenceTo>clofor_com_cfs__CustomObject1__c</referenceTo>
    <relationshipName>Custom_Clearance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/clofor_com_cfs__CustomObject1__c.object-meta.xml
<CustomObject>
    <customHelpPage>clofor_com_cfs__page_HBLOnlineHelp</customHelpPage>
    <description>H B/L SHIPMENT</description>
    <label>F/TMS S/O</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>F/TMS S/O</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETA__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETA__c</fullName>
    <inlineHelpText>If there is no ETA in Document, confirm with Carrier or Co-loader</inlineHelpText>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__ETD__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__CustomObject1__c/fields/clofor_com_cfs__Field1__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Field1__c</fullName>
    <label>CUSTOMER</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS S/O (CUSTOMER)</relationshipLabel>
    <relationshipName>HTqj</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Site_Custom_Settings__c/fields/clofor_com_cfs__Company_Country__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Company_Country__c</fullName>
    <description>The country to consider as &quot;local&quot;. This is driven by HBL SHIPMENT POL-COUNTRY</description>
    <inlineHelpText>The country to consider as local. This is driven by HBL Shipment POL-Country</inlineHelpText>
    <label>Company Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Site_Custom_Settings__c/fields/clofor_com_cfs__FCY_Currency__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__FCY_Currency__c</fullName>
    <label>FCY Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/clofor_com_cfs__Site_Custom_Settings__c/fields/clofor_com_cfs__Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>clofor_com_cfs__Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/clofor_com_cfs__CustomerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Account</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Customer Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/clofor_com_cfs__UnitType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/L</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, gas（at 1031mber and 15℃）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liguefied gas（at abnomal temperature/pressure）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, liquid</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, fineparticles(powders）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, granular particles(grains）</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk, solid, large particles(nodules）</fullName>
    </customValue>
    <customValue>
        <fullName>Bundle</fullName>
    </customValue>
    <customValue>
        <fullName>Cage</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,non-protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
    </customValue>
    <customValue>
        <fullName>Carton</fullName>
    </customValue>
    <customValue>
        <fullName>Case</fullName>
    </customValue>
    <customValue>
        <fullName>Cask</fullName>
    </customValue>
    <customValue>
        <fullName>CBM</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Chest</fullName>
    </customValue>
    <customValue>
        <fullName>Coil</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Crate</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
        <isActive>false</isActive>
        <label>Others</label>
    </customValue>
    <masterLabel>CARGO TYPE(UNIT)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FreighMenoControllerTest.cls
@isTest
public with sharing class FreighMenoControllerTest {
    private static clofor_com_cfs__CustomObject1__c shipment{get; set;}
    private static clofor_com_cfs__AnkenMeisai__c bill{get; set;}
    private static clofor_com_cfs__AnkenMeisai__c customer{get; set;}
    private static List<clofor_com_cfs__AnkenMeisai__c> lstbill{get; set;}
    private static Set<String> setFields = new Set<String>();
    static{
        setFields.add('Name');
    }
    public static testMethod void checkFreighMenoC() {
        
        Test.startTest();
         clofor_com_cfs__Site_Custom_Settings__c scs = new clofor_com_cfs__Site_Custom_Settings__c(clofor_com_cfs__FCY_Currency__c = 'USD',clofor_com_cfs__Local_Currency__c = 'VND',clofor_com_cfs__Company_Country__c = 'Viet Nam');
        insert scs;
        Account ac = new Account(
            Name = 'Customer service',                             // Business Relationship
            Account_Name_JP__c = 'Customer service123123',                                                                   // Account Name
                                                     // Tax Code
                                                  // Customer Type
            clofor_com_cfs__CompanyShortName__c = '495 TO HIEN THANH STR, WARD 14, DISTRICT 10,',  // English Address
            clofor_com_cfs__CustomerType__c = 'Others'                               // Mail
        );
        insert ac;
        
        clofor_com_cfs__CustomObject1__c ship = new clofor_com_cfs__CustomObject1__c(clofor_com_cfs__ETD__c =  Date.newInstance(2021, 1, 1),
                                                  clofor_com_cfs__ETA__c =  Date.newInstance(2021, 3, 20),
                                                                                     clofor_com_cfs__Field1__c = ac.Id);
        insert ship;
        
        clofor_com_cfs__TariffMaster__c ser = new clofor_com_cfs__TariffMaster__c(Name = 'testService');
        insert ser; 
        
        clofor_com_cfs__Custom_Clearance__c cc = new clofor_com_cfs__Custom_Clearance__c(clofor_com_cfs__HBL_SHIPMENT__c = ship.Id);
        insert cc;
        
        List<clofor_com_cfs__AnkenMeisai__c> lstBill  = new List<clofor_com_cfs__AnkenMeisai__c>();
        clofor_com_cfs__AnkenMeisai__c bill = new clofor_com_cfs__AnkenMeisai__c(clofor_com_cfs__Anken__c =ship.Id,
                                                                                 clofor_com_cfs__Seikyusaki__c= ac.Id,
                                                                                 clofor_com_cfs__Tariff__c =ser.Id,
                                                                                 clofor_com_cfs__Description__c  = 'testDescription12345',
                                                                                 clofor_com_cfs__Suryo__c = 2,
                                                                                 clofor_com_cfs__SellTankaUSD__c = 120000,
                                                                                 clofor_com_cfs__ChargeUnit__c = 'CBM',
                                                                                 clofor_com_cfs__PrintFlag__c = true
                                                                                );
         lstBill.add(bill);
        clofor_com_cfs__AnkenMeisai__c bill2 = new clofor_com_cfs__AnkenMeisai__c(clofor_com_cfs__Anken__c =ship.Id,
                                                                                 clofor_com_cfs__Tariff__c =ser.Id,
                                                                                 clofor_com_cfs__Description__c  = 'testDescription1',
                                                                                 clofor_com_cfs__Suryo__c = 111,
                                                                                 clofor_com_cfs__SellTankaUSD__c = 1001001,
                                                                                 clofor_com_cfs__ChargeUnit__c = 'CBM',
                                                                                 
                                                                                 clofor_com_cfs__Seikyusaki__c = ac.Id
                                                                                );
        lstBill.add(bill2);
        insert lstBill;
       
        clofor_com_cfs__Container_Info__c conf1 = new clofor_com_cfs__Container_Info__c(clofor_com_cfs__Container_NO__c = 'number test 123',clofor_com_cfs__Seal_No__c = 'seal number 123',clofor_com_cfs__Container__c = 'container', clofor_com_cfs__QUANTITY_PACKAGES__c = 1, clofor_com_cfs__GROSS_WEIGHT__c = 2, clofor_com_cfs__MEASUREMENT_CBM__c = 3, clofor_com_cfs__HBL_SHIPMENT__c = ship.Id);
        insert conf1;
        
        PageReference pageRef = Page.page_FreighMeno;
        pageRef.getParameters().put('Id', ship.Id);
        Test.setCurrentPage(pageRef);
        FreighMenoController fe = new FreighMenoController();
        
        ApexPages.currentPage().getParameters().put('shipmentId', ship.Id);
        //fe.stringQueryShipment() = [SELECT Id, Name FROM clofor_com_cfs__CustomObject1__c WHERE Id =: shipmentId LIMIT 1];
        //List<clofor_com_cfs__AnkenMeisai__c> lstbill = fe.stringQueryBill(ship.Id);
        //fe.redirPage();
        List<SelectOption> itemOptions = fe.getCustomerList();
        List<SelectOption> fileOptions = fe.getFileTypeOptions();
        // List<SelectOption> invoiceNoOptions = taxInvoice.getInvoiceNoOptions(); 
        Test.stopTest();
}
}